# Super Store Sales Data Dashboard

## Overview
This repository contains a Power BI dashboard analyzing sales data from a superstore. The dashboard provides insights into key metrics such as total profit, quantity sold, product distribution, 
and regional sales performance.

## Features
- Total Profit Analysis: Displays overall profit generated by the store.
- Sales by Region: Visualizes sales performance across different geographical regions.
- Product Category Analysis: Highlights product distribution and sales based on sub-categories.
- Profit by Customer: Identifies the most profitable customers.
- Sales Trends: Analyzes sales performance over different years and months.

## Dashboard Features & Charts

1) Total Profit Analysis
- Displays overall profit generated by the store to help understand profitability trends.

2) Sales by Region
- Visualizes sales performance across different geographical regions.
- Helps identify the strongest and weakest performing regions.

3) Product Category Analysis
- Highlights product distribution and sales based on sub-categories.
- Useful for inventory and marketing decisions.

4) Profit by Customer
- Identifies the most profitable customers.
- Helps in customer retention strategies and loyalty programs.

5) Sales Trends
- Analyzes sales performance over different years and months.
- Helps in identifying seasonal sales trends and forecasting future sales.

## Dataset
The dataset includes:
- Sales, profit, and quantity data
- Product categories and sub-categories
- Customer and regional sales data

## Visualization Tool
The dashboard is created using Power BI Desktop.

## Contact
For any questions or suggestions, feel free to open an issue or reach out via GitHub.

How to Use the Dashboard
 - Open the .pbix file in Power BI Desktop.
 - Interact with filters, slicers, and charts to analyze restaurant trends.
 - Gain insights into sales performance, customer behavior, and restaurant operations.
 - Export or share reports via Power BI Service.

